"""rescue_utility

Revision ID: d8304f547526
Revises: e19d5fb2938b
Create Date: 2025-04-11 22:20:46.107743

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd8304f547526'
down_revision: str | None = 'e19d5fb2938b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('rescue', sa.Integer(), nullable=False))
    op.add_column('locations', sa.Column('utlity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'utlity')
    op.drop_column('locations', 'rescue')
    # ### end Alembic commands ###
