version: "3.9"

services:
  db:
    image: postgres:15
    container_name: emergency_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  algorithm:
    build:
      context: .
    container_name: emergency_algorithm
    env_file: .env
    depends_on:
      - db
    command: python main_refactor.py
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data: